##Configurado para o Lambda
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:20

COPY --from=builder /app/dist ./dist
COPY package*.json ./
RUN npm install --omit=dev

CMD ["dist/src/lambda.handler"]